### ISSUE TITLE
Bomb respawn timer changes are lost on reload

### ISSUE THREAD

**Issue by c0wg0d** [Europia79/Demolition#3]
If I change the bomb respawn timer to 5 seconds, it works fine until the server is restarted or /bomb reload is called, then it goes back to the default 500.  Even if I change it in BombArenaConfig.yml the changes are lost.  Can you either support letting us change the respawn timer or at least respawn the bomb automatically if it gets destroyed in lava/cactus/etc.?

**Comment by Europia79** [comment]
You changed it via commands ?

Can you stop the server, edit the config.yml, save it, and check that way ?

i'll take a look at the respawn logic & commands.

**Comment by Europia79** [comment]
Sorry, i think you would have to edit ```/plugins/BombArena/arenas.yml```
```yaml
arenas:
  bomb1:
    waitRoomLocations:
      '0':
      - world,-429.74615478515625,4.0,-1206.3194580078125,-354.8993,3.599917
      '1':
      - world,-429.74615478515625,4.0,-1206.3194580078125,-354.8993,3.599917
    locations:
      '0':
      - world,-463.1009826660156,4.0,-1219.360595703125,-93.899414,2.0999312
      '1':
      - world,-399.3763122558594,4.0,-1221.9786376953125,-276.14932,-1.9500805
    persistable:
      savedBases:
      - world,-401.0,4.0,-1221.0,0.0,0.0
      - world,-462.0,4.0,-1221.0,0.0,0.0
    type: BombArena
    spawns:
      '1':
        loc: world,-429.4585266113281,4.0,-1220.51611328125,-271.79935,-0.90008795
        spawn: REDSTONE_BLOCK 1
        time: 1 65 65
    params:
      victoryCondition: NoTeamsLeft
  snd1:
    waitRoomLocations:
      '0':
      - world,-426.3664855957031,4.0,-1205.9754638671875,-1.1900545,8.2499895
      '1':
      - world,-426.3664855957031,4.0,-1205.9754638671875,-1.1900545,8.2499895
    locations:
      '0':
      - world,-461.39178466796875,4.0,-1221.6190185546875,-89.24011,6.449858
      '1':
      - world,-400.01934814453125,4.0,-1222.046630859375,89.25996,4.649859
    persistable:
      savedBases:
      - world,-401.0,4.0,-1221.0,0.0,0.0
      - world,-462.0,4.0,-1221.0,0.0,0.0
      wgRegion: world,ba-snd1
    type: SndArena
    spawns:
      '1':
        loc: world,-452.2074890136719,4.0,-1220.843994140625,91.80993,10.199982
        spawn: REDSTONE_BLOCK 1
        time: 1 45 45
    params: {}
brokenArenas: {}
```
http://wiki.battleplugins.org/BattleArena/Spawns
https://github.com/Europia79/Demolition/blob/master/src/main/java/mc/euro/demolition/commands/Command.java#L24-L25
You have to change the ```time:``` node. 
The 1st number is "First spawn".
The 2nd number is "Respawn"
The 3rd number is "Despawn"
So, you have to change the 2nd number to 5.

Here's the despawn logic:
https://github.com/Europia79/Demolition/blob/master/src/main/java/mc/euro/demolition/arenas/EodArena.java#L220-L245
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/ItemDespawnEvent.html
```java
    /**
     * This method makes sure that the bomb doesn't despawn during a match. <br/><br/>
     * 
     * <pre>
     * - is the item a bomb ?
     * - ok, does someone already have the bomb in their inventory ?
     * - if not, cancel the ItemDespawnEvent.
     * </pre>
     * @param e ItemDespawnEvent - Was it the bomb ? Or another item ?
     */
    @ArenaEventHandler(needsPlayer = false)
    public void onBombDespawn(ItemDespawnEvent e) {
        Material mat = e.getEntity().getItemStack().getType();
        if (mat != plugin.getBombBlock()) {
            return;
        }

        if (carrier == null) {
            Set<ArenaPlayer> allplayers = getMatch().getPlayers();
            plugin.debug.log("Bomb despawn cancelled.");
            e.setCancelled(true);
        } else {
            plugin.debug.log("Bomb despawn allowed because " + carrier + " has the bomb.");
        }

    } // END OF ItemDespawnEvent
```
